// Official source pages and embeds checked on 2026-09-07.
// Live video IDs may change; always keep the source-page fallback.
export const cameras = [
  { id: 'camelthorn', name: '卡梅尔索恩水塘', country: '博茨瓦纳', region: '博泰蒂河畔', en: 'CAMELTHORN', provider: 'AFRICAM', timezone: 'Africa/Gaborone', coordinates: 'BOTETI RIVER · BOTSWANA', species: '大象、斑马与河马', tag: '草原水塘', source: 'https://africam.com/lodge/camelthorn/', embed: 'https://www.youtube.com/embed/mk02pEy3FdA', image: 'https://africam-lodge-thumbnails.s3.eu-west-2.amazonaws.com/26_08_2026/elephants_paying_in_the_water_ct_29_08_2026.jpg', note: '水塘是草原的会客厅。慢一点，等一位路过的朋友。' },
  { id: 'albatross', name: '皇家信天翁', country: '新西兰', region: '泰瓦罗瓦角', en: 'ROYAL ALBATROSS', provider: 'CORNELL LAB', timezone: 'Pacific/Auckland', coordinates: 'TAIAROA HEAD · NEW ZEALAND', species: '北方皇家信天翁', tag: '海岸鸟巢', source: 'https://www.allaboutbirds.org/cams/royal-albatross/', embed: 'https://www.youtube.com/embed/Mm_zVDDUeNA', image: 'https://www.allaboutbirds.org/cams/wp-content/uploads/2019/12/Albatross_1200x630.jpg', note: '海风吹过鸟巢。这里的主角，是一位来自南半球的远洋旅行家。' },
  { id: 'panda', name: '成都大熊猫', country: '中国', region: '成都大熊猫繁育研究基地', en: 'CHENGDU PANDA', provider: 'IPANDA', timezone: 'Asia/Shanghai', coordinates: 'CHENGDU · CHINA', species: '大熊猫', tag: '熊猫基地', source: 'https://www.youtube.com/watch?v=SUXPnIEpbn4', embed: 'https://www.youtube.com/embed/SUXPnIEpbn4', image: 'https://i.ytimg.com/vi/SUXPnIEpbn4/hqdefault.jpg', note: '使用 iPanda 官方 YouTube 直播入口。' },
  { id: 'cornell-feeders', name: '康奈尔林间鸟食台', country: '美国', region: '纽约州 · 伊萨卡', en: 'CORNELL FEEDERS', provider: 'CORNELL LAB', timezone: 'America/New_York', coordinates: 'ITHACA · NEW YORK', species: '啄木鸟、山雀与红翅黑鹂', tag: '林间食堂', source: 'https://www.allaboutbirds.org/cams/cornell-lab-feederwatch/', embed: 'https://www.youtube.com/embed/x10vL6_47Dw', image: 'https://www.allaboutbirds.org/cams/wp-content/uploads/2019/08/Cornell-Feeders_1200x630.jpg', note: '林间食台的访客会随季节与时段变化。' },
  { id: 'panama-fruit', name: '巴拿马雨林水果台', country: '巴拿马', region: '安东谷 · Canopy Lodge', en: 'PANAMA FRUIT FEEDERS', provider: 'CORNELL LAB', timezone: 'America/Panama', coordinates: 'EL VALLE DE ANTON · PANAMA', species: '唐纳雀、巨嘴鸟等热带鸟类', tag: '雨林访客', source: 'https://www.allaboutbirds.org/cams/panama-fruit-feeders/', embed: 'https://www.youtube.com/embed/WtoxxHADnGk', image: 'https://www.allaboutbirds.org/cams/wp-content/uploads/2019/08/Panama_1200x630.jpg', note: '看看今天谁来分享一份水果。' },
  { id: 'panama-hummingbirds', name: '巴拿马蜂鸟驿站', country: '巴拿马', region: '索韦拉尼亚国家公园', en: 'PANAMA HUMMINGBIRDS', provider: 'CORNELL LAB', timezone: 'America/Panama', coordinates: 'SOBERANIA · PANAMA', species: '蜂鸟', tag: '蜂鸟驿站', source: 'https://www.allaboutbirds.org/cams/panama-hummingbird-feeders/', embed: 'https://www.youtube.com/embed/0xFARCdZ3vA', image: 'https://www.allaboutbirds.org/cams/wp-content/uploads/2025/04/PanamaHummingbirds.jpg', note: 'Canopy Tower 的小小访客，来去都很轻快。' },
  { id: 'hellgate-ospreys', name: '赫尔盖特鱼鹰巢', country: '美国', region: '蒙大拿州 · 米苏拉', en: 'HELLGATE OSPREYS', provider: 'CORNELL LAB', timezone: 'America/Denver', coordinates: 'MISSOULA · MONTANA', species: '鱼鹰', tag: '河畔鸟巢', source: 'https://www.allaboutbirds.org/cams/hellgate-ospreys/', embed: 'https://www.youtube.com/embed/-qvYCbvbeN8', image: 'https://www.allaboutbirds.org/cams/wp-content/uploads/2019/08/Hellgate_1200x630.jpg', note: '鱼鹰会离巢捕食，也会随季节迁徙。' },
  { id: 'tembe-elephants', name: '坦贝大象水塘', country: '南非', region: '夸祖鲁-纳塔尔省 · 马普托兰', en: 'TEMBE ELEPHANT PARK', provider: 'AFRICAM', timezone: 'Africa/Johannesburg', coordinates: 'MAPUTALAND · SOUTH AFRICA', species: '非洲象与水塘访客', tag: '大象水塘', source: 'https://africam.com/lodge/tembe-elephant-park/', embed: 'https://www.youtube.com/embed/gdrNUUf-cQw', image: 'https://africam.com/wp-content/webp-express/webp-images/uploads/2024/11/Lodge-YT-Stream-12.png.webp', note: '镜头守着水塘，动物会自由来去。' },
  { id: 'stony-point-penguins', name: '斯托尼角企鹅海岸', country: '南非', region: '贝蒂湾 · 斯托尼角', en: 'STONY POINT PENGUINS', provider: 'AFRICAM', timezone: 'Africa/Johannesburg', coordinates: 'BETTYS BAY · SOUTH AFRICA', species: '非洲企鹅', tag: '企鹅海岸', source: 'https://africam.com/lodge/penguins/', embed: 'https://www.youtube.com/embed/NiwrvhQIHIo', image: 'https://africam.com/wp-content/webp-express/webp-images/uploads/2024/12/Untitled-design-9.png.webp', note: '在海岸栖息地等待企鹅经过。' },
];
